# Generated by Django 5.1.4 on 2025-01-06 18:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=300)),
                ('titulo', models.CharField(max_length=100)),
                ('data_criacao', models.DateTimeField(verbose_name='date published')),
                ('data_atualizacao', models.DateTimeField(verbose_name='date update')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lista', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Tarefa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('descricao', models.CharField(max_length=300, null=True)),
                ('dataCriacao', models.DateField(verbose_name='date published')),
                ('dataConclusao', models.DateField(blank=True, null=True, verbose_name='date con')),
                ('status', models.CharField(choices=[('concluido', 'concluido'), ('em andamento', 'em andamento'), ('pendente', 'pendente')], max_length=20, null=True)),
                ('prioridade', models.CharField(choices=[('alta', 'alta'), ('media', 'media'), ('baixa', 'baixa')], max_length=20, null=True)),
                ('dataVencimento', models.DateField(null=True, verbose_name='date final')),
                ('lista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='todo.lista')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
